import type { PriceEntry } from "./prices.ts";

export interface PriceMeta {
  generatedAt: number; // unix seconds, compared against the game's time()
  source: string;
}

export function luaString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\0/g, "\\0");
  return `"${escaped}"`;
}

// Must stay in step with what the addon expects: ns.priceMeta and ns.prices
// keyed by item id, values in copper.
export function renderPriceData(entries: PriceEntry[], meta: PriceMeta): string {
  const sorted = [...entries].sort((a, b) => a.itemId - b.itemId);
  const rows = sorted.map((entry) => {
    const comment = entry.note ? ` -- ${entry.note.replace(/[\r\n]+/g, " ")}` : "";
    return `  [${entry.itemId}] = ${entry.copper},${comment}`;
  });
  return [
    "-- Generated by tools/src/build-data.ts. Don't edit by hand: edit data/prices.csv and rerun.",
    "local _, ns = ...",
    "",
    `ns.priceMeta = { generatedAt = ${Math.floor(meta.generatedAt)}, source = ${luaString(meta.source)}, count = ${sorted.length} }`,
    "",
    "ns.prices = {",
    ...rows,
    "}",
    "",
  ].join("\n");
}
