-- Generated by tools/src/build-data.ts. Don't edit by hand: edit data/prices.csv and rerun.
local _, ns = ...

ns.priceMeta = { generatedAt = 1790278514, source = "prices.csv", count = 0 }

ns.prices = {
}
